name: Waka Readme

on:
  schedule:
    # Runs at 12:00 AM UTC every day
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  update-readme:
    name: Update Readme with Metrics
    runs-on: ubuntu-latest
    steps:
      - uses: anmol098/waka-readme-stats@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKA_SECRET }}
          GH_TOKEN: ${{ secrets.GH_SECRET }}
          # hidden some options for brevity
          SHOW_PROJECTS: "False"
          SHOW_OS: "False"
          SHOW_SHORT_INFO: "False"
          SHOW_LOC_CHART: "False"
          SHOW_EDITORS: "False"
          SHOW_TIMEZONE: "False"
          SHOW_UPDATED_DATE: "False"
          SHOW_LANGUAGE_PER_REPO: "False"
          SHOW_LANGUAGE: "False"
          SHOW_DAYS_OF_WEEK: "False"
